module ApiResponseCode
  SUCCESS = 200
  BAD_REQUEST = 400
  UNAUTHORIZED = 401
  FORBIDDEN = 403
  NOT_FOUND = 404
  UNPROCESSABLE_ENTITY = 422
  INTERNAL_SERVER_ERROR = 500
  WISHLIST_CREATED_SUCCESSFULLY = 201
  WISHLIST_CREATION_FAILED = 422
  WISHLIST_UPDATED_SUCCESSFULLY = 202
  WISHLIST_UPDATE_FAILED = 423
  LOCALEXPERIENCE_CREATED_SUCCESSFULLY = 200
  LOCALEXPERIENCE_CREATION_FAILED_BAD_REQUEST = 400
  LOCALEXPERIENCE_CREATION_FAILED_UNAUTHORIZED = 401
  LOCALEXPERIENCE_CREATION_FAILED_FORBIDDEN = 403
  LOCALEXPERIENCE_CREATION_FAILED_UNPROCESSABLE_ENTITY = 422
  LOCALEXPERIENCE_CREATION_FAILED_INTERNAL_SERVER_ERROR = 500
  DELETE_LOCAL_EXPERIENCE_SUCCESS = 200
  DELETE_LOCAL_EXPERIENCE_BAD_REQUEST = 400
  DELETE_LOCAL_EXPERIENCE_UNAUTHORIZED = 401
  DELETE_LOCAL_EXPERIENCE_FORBIDDEN = 403
  DELETE_LOCAL_EXPERIENCE_UNPROCESSABLE_ENTITY = 422
  DELETE_LOCAL_EXPERIENCE_INTERNAL_SERVER_ERROR = 500
end
